filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/*.log

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: ["http://elasticsearch.local:9200"]  # TODO: Replace with Elasticsearch endpoint
  index: "honeypot-logs-%{+yyyy.MM.dd}"

setup.kibana:
  host: "http://kibana.local:5601" 

setup.template.name: "my-honeypot-template"  # Custom template name
setup.template.pattern: "my-honeypot-*"      # Custom index pattern


logging:
  level: info
  to_files: true
  files:
    path: /logs/filebeat
    name: filebeat
    keepfiles: 7
    permissions: 0644